import Head from "next/head";
import {
  Geist,
  Geist_Mono,
  Montserrat,
  Playfair_Display,
} from "next/font/google";
import {
  Header,
  Banner,
  OurGame,
  OurPartner,
  AboutUs,
  Footer,
  Copyright,
} from "@/components";
import ScrollDown from "@/components/scroll-down";

const montserrat = Montserrat({
  variable: "--montserrat",
  subsets: ["latin"],
});
const playFair = Playfair_Display({
  variable: "--playFair",
  subsets: ["latin"],
});

export async function getStaticProps(context) {
  return {
    props: {
      // You can get the messages from anywhere you like. The recommended
      // pattern is to put them in JSON files separated by locale and read
      // the desired one based on the `locale` received from Next.js.
      messages: (await import(`../locale/${context.locale}.json`)).default,
    },
  };
}

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${montserrat.variable} ${playFair.variable} main-wrapper`}
      >
        <Header />
        <Banner />
        <AboutUs />
        <OurGame />
        <Footer />
        <ScrollDown />
      </div>
    </>
  );
}
